/*
 * This source file was generated by the Gradle 'init' task
 */
package project.ticket.booking;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertNotNull;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
       
    }
}
